module.exports = [
  {
    name: 'Asprin and Caffeine',
    company: 'Insight Pharmaceuticals',
    strength: 10,
    instructions: 'Drainage of Hemiazygos Vein, Percutaneous Endoscopic Approach',
    reason: 'Unspecified superficial injury of right ankle, init encntr',
  },
  {
    name: 'Quinine Sulfate',
    company: 'Mutual Pharmaceutical Company, Inc.',
    strength: 4,
    instructions:
      'Insertion of Infusion Device into Right External Iliac Artery, Percutaneous Endoscopic Approach',
    reason: 'Other specified injury of superior mesenteric vein',
  },
  {
    name: 'Neomycin Sulfate, Polymyxin B Sulfate, Hydrocortisone',
    company: 'Rebel Distributors Corp',
    strength: 12,
    instructions:
      'Replacement of Right Tympanic Membrane with Nonautologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic',
    reason: 'Laceration of unsp kidney, unspecified degree, subs encntr',
  },
  {
    name: 'Watermelon',
    company: 'Nelco Laboratories, Inc.',
    strength: 7,
    instructions:
      'Restriction of Pulmonary Trunk with Intraluminal Device, Percutaneous Endoscopic Approach',
    reason: 'Toxic eff of harmful algae and algae toxins, slf-hrm, sqla',
  },
  {
    name: 'Treatment Set TS351003',
    company: 'Antigen Laboratories, Inc.',
    strength: 11,
    instructions: 'Repair Stomach, Via Natural or Artificial Opening Endoscopic',
    reason: 'Unsp bus occupant injured in clsn w unsp mv nontraf, init',
  },
  {
    name: 'Nutmeg',
    company: 'Nelco Laboratories, Inc.',
    strength: 15,
    instructions:
      'Replacement of Epiglottis with Synthetic Substitute, Via Natural or Artificial Opening Endoscopic',
    reason: 'Corros second degree of unsp mult fngr, inc thumb, sqla',
  },
  {
    name:
      'ambrosia psilostachya pollen and ambrosia trifida pollen and ambrosia artemisiifolia pollen',
    company: 'Allergy Laboratories, Inc.',
    strength: 10,
    instructions: 'Resection of Bilateral Adrenal Glands, Percutaneous Endoscopic Approach',
    reason: 'Generalized anxiety disorder',
  },
  {
    name: 'PYRITHIONE ZINC',
    company: 'SAFEWAY INC',
    strength: 12,
    instructions: 'Insertion of Internal Fixation Device into Right Tibia, Open Approach',
    reason: 'Laceration with foreign body of right hand, init encntr',
  },
  {
    name: 'Metoprolol Tartrate',
    company: 'REMEDYREPACK INC.',
    strength: 20,
    instructions: 'Low Dose Rate (LDR) Brachytherapy of Bronchus using Other Isotope',
    reason: 'Anaphylactic reaction due to oth food products, subs encntr',
  },
  {
    name: 'Sucralfate',
    company: 'PD-Rx Pharmaceuticals, Inc.',
    strength: 8,
    instructions: 'Revision of Internal Fixation Device in Right Metacarpal, External Approach',
    reason: 'Displ transverse fx right patella, init for opn fx type I/2',
  },
  {
    name: 'haloperidol',
    company: 'REMEDYREPACK INC.',
    strength: 4,
    instructions: 'Introduction of Anti-inflammatory into Mouth and Pharynx, Percutaneous Approach',
    reason: 'Glaucoma secondary to other eye disorders',
  },
  {
    name: 'Acetaminophen, Diphenhydramine HCl and Phenylephrine HCl',
    company: 'Target Corporation',
    strength: 15,
    instructions: 'Replacement of Left Breast with Nonautologous Tissue Substitute, Open Approach',
    reason: 'Displaced comminuted fracture of shaft of ulna, unsp arm',
  },
  {
    name: 'Treatment Set TS331327',
    company: 'Antigen Laboratories, Inc.',
    strength: 19,
    instructions: 'Repair Left Lower Arm and Wrist Muscle, Open Approach',
    reason: 'Displ transverse fx shaft of humer, unsp arm, 7thP',
  },
  {
    name: 'Diclofenac Sodium',
    company: 'BluePoint Laboratories',
    strength: 5,
    instructions: 'Intraoperative Radiation Therapy (IORT) of Stomach',
    reason: 'Sltr-haris Type III physeal fx phalanx of right toe, init',
  },
  {
    name: 'Doxazosin Mesylate',
    company: 'DAVA Pharmaceuticals, Inc.',
    strength: 5,
    instructions: 'Excision of Duodenum, Percutaneous Endoscopic Approach, Diagnostic',
    reason: 'Malignant neoplasm of scapula and long bones of upper limb',
  },
  {
    name: 'Hydrocortisone',
    company: 'Valu Merchandisers, Co.',
    strength: 1,
    instructions: 'Extirpation of Matter from Left Extraocular Muscle, External Approach',
    reason: 'Dislocation of radiocarpal joint of left wrist, init encntr',
  },
  {
    name: 'Octinoxate',
    company: "L'Oreal USA Products Inc",
    strength: 16,
    instructions:
      'Therapeutic Exercise Treatment of Musculoskeletal System - Lower Back / Lower Extremity using Electrotherapeutic Equipment',
    reason: 'Injury of superficial palmar arch',
  },
  {
    name: 'ertapenem sodium',
    company: 'Merck Sharp & Dohme Corp.',
    strength: 2,
    instructions:
      'Revision of Autologous Tissue Substitute in Right Metacarpal, Percutaneous Approach',
    reason: 'Drown due to fall/jump fr burning merchant ship, init',
  },
  {
    name: 'ARIPIPRAZOLE',
    company: 'Carilion Materials Management',
    strength: 9,
    instructions:
      'Replacement of Bilateral External Ear with Synthetic Substitute, External Approach',
    reason: 'Fracture of unsp carpal bone, right wrist, init for clos fx',
  },
  {
    name: 'AVOBENZONE HOMOSALATE OCTISALATE OCTOCRYLENE OXYBENZONE',
    company: 'THE KROGER CO',
    strength: 2,
    instructions: 'Resection of Spleen, Percutaneous Endoscopic Approach',
    reason: 'Pnctr of abd wall w fb, l upr q w/o penet perit cav, sequela',
  },
  {
    name: 'Imipramine Hydrochloride',
    company: 'Bryant Ranch Prepack',
    strength: 5,
    instructions: 'Drainage of Right Buttock, Percutaneous Approach, Diagnostic',
    reason: 'Disp fx of lateral condyle of l tibia, 7thN',
  },
  {
    name: 'candida parapsilosis',
    company: 'Sanum Kehlbeck GmbH & Co. KG',
    strength: 16,
    instructions: 'Stereotactic Particulate Radiosurgery of Thymus',
    reason: 'Displ subtrochnt fx unsp femur, init for opn fx type 3A/B/C',
  },
  {
    name: 'Aluminum hydroxide, Magnesium hydroxide, Simethicone',
    company: 'Rij Pharmaceutical Corporation',
    strength: 16,
    instructions: 'Beam Radiation of Pelvic Bones using Electrons, Intraoperative',
    reason: 'Gastric diverticulum',
  },
  {
    name: 'Metolazone',
    company: 'NCS HealthCare of KY, Inc dba Vangard Labs',
    strength: 16,
    instructions: 'Repair Pons, Percutaneous Approach',
    reason: 'Poisoning by chloramphenicol group, assault, init encntr',
  },
  {
    name: 'Omeprazole',
    company: "Sam's West Inc",
    strength: 19,
    instructions:
      'Replacement of Left Foot Artery with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Burn of first degree of right elbow, sequela',
  },
  {
    name: 'Ketorolac Tromethamine',
    company: 'Sun Pharma Global Inc.',
    strength: 12,
    instructions: 'Dilation of Cystic Duct, Via Natural or Artificial Opening Endoscopic',
    reason: 'Saccadic eye movements',
  },
  {
    name: 'TOLNAFTATE',
    company: 'CARDINAL HEALTH',
    strength: 9,
    instructions: 'Removal of Stimulator Lead from Lower Muscle, External Approach',
    reason: 'Other specified injury of superficial palmar arch',
  },
  {
    name: 'Ibuprofen, Pseudoephedrine Hydrochloride',
    company: 'Dispensing Solutions, Inc.',
    strength: 7,
    instructions: 'Dilation of Left Ulnar Artery, Bifurcation, Percutaneous Endoscopic Approach',
    reason: 'Intestinal bypass and anastomosis status',
  },
  {
    name: 'Aluminum Hydroxide, Magnesium Hydroxide, Simethicone',
    company: 'Kroger Company',
    strength: 13,
    instructions: 'Excision of Left Internal Jugular Vein, Open Approach',
    reason: 'Gout due to renal impairment, unspecified hand',
  },
  {
    name: 'Halcinonide',
    company: 'E.R. Squibb & Sons, L.L.C.',
    strength: 17,
    instructions:
      'Insertion of Intraluminal Device into Right Common Iliac Vein, Percutaneous Approach',
    reason: 'Complications associated with artificial fertilization',
  },
  {
    name: 'methylprednisolone sodium succinate',
    company: 'Cardinal Health',
    strength: 9,
    instructions:
      'Insertion of Infusion Device into Right Hand Artery, Percutaneous Endoscopic Approach',
    reason: 'Leakage of internal prosth dev/grft, init',
  },
  {
    name:
      'PAEONIA OFFICINALIS, RATANHIA, NITRICUM ACIDUM, SULFUR, PODOPHYLLUM PELTATUM, RUTA GRAVEOLENS, GRAPHITES, APIS MELLIFICA, AESCULUS HIPPOCASTANUM, NUX VOMICA',
    company: 'HOMEOLAB USA INC',
    strength: 10,
    instructions:
      'Replacement of Left Upper Leg Tendon with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Unspecified physeal fracture of lower end of left fibula',
  },
  {
    name: 'LEVETIRACETAM',
    company: 'STAT RX USA LLC',
    strength: 11,
    instructions:
      'Insertion of Monitoring Device into Spinal Cord, Percutaneous Endoscopic Approach',
    reason: 'Other contact with orca',
  },
  {
    name: 'Simvastatin',
    company: 'McKesson Packaging Services a business unit of McKesson Corporation',
    strength: 12,
    instructions:
      'Dilation of Right Ulnar Artery, Bifurcation, with Four or More Intraluminal Devices, Percutaneous Endoscopic Approach',
    reason: 'Toxic effect of contact w sea anemone, assault, subs encntr',
  },
  {
    name: 'Oxygen',
    company: 'Hometown Medical LLC',
    strength: 15,
    instructions: 'Release Right Inner Ear, Open Approach',
    reason: 'Nondisp spiral fx shaft of r femr, 7thG',
  },
  {
    name: 'PYRITHIONE ZINC',
    company: 'SALERM COSMETICA PROFESIONAL, S.A.',
    strength: 8,
    instructions: 'Removal of Infusion Device from Cisterna Chyli, Percutaneous Approach',
    reason: 'Exposure to smoke, fire and flames, undet intent, sequela',
  },
  {
    name: 'POTASSIUM BICARBONATE',
    company: 'Qualitest Pharmaceuticals',
    strength: 11,
    instructions:
      'Dilation of Right Posterior Tibial Artery with Three Drug-eluting Intraluminal Devices, Open Approach',
    reason: 'Occ of anml-drn vehicle inj in clsn w statnry object, init',
  },
  {
    name: 'cyclobenzaprine hydrochloride',
    company: 'American Health Packaging',
    strength: 2,
    instructions: 'Bypass Left Atrium to Right Pulmonary Vein, Percutaneous Endoscopic Approach',
    reason: 'Contracture of muscle, right shoulder',
  },
  {
    name: 'Carbinoxamine maleate',
    company: 'Hawthorn Pharmaceuticals, Inc.',
    strength: 9,
    instructions:
      'Supplement Larynx with Autologous Tissue Substitute, Via Natural or Artificial Opening',
    reason: 'Myelodysplastic syndrome w isolated del(5q) chromsoml abnlt',
  },
  {
    name: 'risperidone',
    company: 'Cadila Healthcare Limited',
    strength: 5,
    instructions: 'Excision of Right External Iliac Artery, Percutaneous Endoscopic Approach',
    reason: 'Person injured wh brd/alit from oth sp off-rd mv, sequela',
  },
  {
    name:
      'Adenosinum cyclophosphoricum, Adrenalinum, Adrenocorticotrophin, Alfalfa, Allium cepa, Bellis perennis, Conium maculatum, Cortisone aceticum, Equisetum hyemale, Euphrasia officinalis, Fagopyrum esculentum, Galphimia glauca, Histaminum hydrochloricum, Kali muriaticum, Millefolium, Mucosa nasalis suis, Natrum muriaticum, Prunus spinosa, RNA, Sabadilla, Solidago virgaurea',
    company: 'King Bio Inc.',
    strength: 6,
    instructions: 'Excision of Thoracolumbar Vertebral Joint, Percutaneous Endoscopic Approach',
    reason: 'Oth periradicular pathology assoc w prev endodontic trtmt',
  },
  {
    name: 'omeprazole, sodium bicarbonate',
    company: 'Physicians Total Care, Inc.',
    strength: 7,
    instructions: 'Drainage of Right Hip Tendon, Open Approach, Diagnostic',
    reason: 'Unsp injury of intercostal blood vessels, left side, subs',
  },
  {
    name: 'Ethanol, Triclosan',
    company: 'RWM TECHNOLOGIES',
    strength: 6,
    instructions:
      'Bypass Left Internal Iliac Artery to Foot Artery with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Stress fracture, left hand, subs for fx w nonunion',
  },
  {
    name: 'Adenosine',
    company: 'Akorn, Inc.',
    strength: 16,
    instructions: 'Supplement Left Hip Bursa and Ligament with Synthetic Substitute, Open Approach',
    reason: 'Displ oblique fx shaft of unsp femr, 7thR',
  },
  {
    name:
      'Pyrogenium, Antimon. crud., Arsenicum alb., Baptisia, Bryonia, Carbo veg.,Chelidonium majus, Cinchona, Colchicum, Daphne indica, Ipecac., Iris versicolor, Kali carb.,Kreosotum, Lachesis, Lycopodium, Mag. carb., Merc. viv, Nux vom., Phosphorus, Pulsatilla, Spigelia anth., Sulphur, Chamomilla, Echinacea, Ruta, Taraxacum',
    company: 'Newton Laboratories, Inc.',
    strength: 19,
    instructions:
      'Bypass Left Femoral Artery to Popliteal Artery with Autologous Venous Tissue, Open Approach',
    reason: 'War op w dest arcrft due to onboard fire, civilian, init',
  },
  {
    name: 'HYDROQUINONE',
    company: 'International Beauty Exchange',
    strength: 17,
    instructions: 'Insertion of Internal Fixation Device into Left Rib, Open Approach',
    reason: 'Chronic osteomyelitis with draining sinus, right shoulder',
  },
  {
    name: 'Oxycodone Hydrochloride',
    company: 'Lehigh Valley Technologies, Inc.',
    strength: 17,
    instructions: 'Revision of Synthetic Substitute in Right Glenoid Cavity, External Approach',
    reason: 'Contact with nonvenomous marine animal',
  },
  {
    name: 'Levetiracetam',
    company: 'Rebel Distributors Corp',
    strength: 9,
    instructions: 'Drainage of Head and Neck Bursa and Ligament, Percutaneous Endoscopic Approach',
    reason: 'Path fracture in neoplastic disease, l humerus, sequela',
  },
  {
    name: 'isosorbide mononitrate',
    company: 'Bryant Ranch Prepack',
    strength: 7,
    instructions:
      'Bypass Coronary Artery, Three Arteries from Abdominal Artery with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Dislocation of other parts of thorax, sequela',
  },
  {
    name: 'risperidone',
    company: 'Janssen Pharmaceutical, Inc.',
    strength: 2,
    instructions: 'Drainage of Left Lacrimal Bone, Open Approach',
    reason: 'Late congenital syphilis, unspecified',
  },
  {
    name: 'pioglitazone hydrochloride',
    company: 'Dispensing Solutions, Inc.',
    strength: 3,
    instructions:
      'Supplement Right External Iliac Vein with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Fracture of unsp part of scapula, right shoulder, init',
  },
  {
    name: 'TITANIUM DIOXIDE',
    company: 'CHANEL PARFUMS BEAUTE',
    strength: 5,
    instructions:
      'Bypass Coronary Artery, Four or More Arteries from Thoracic Artery with Synthetic Substitute, Open Approach',
    reason: 'Poisoning by sulfonamides, undetermined, subs encntr',
  },
  {
    name: 'Dextromethorphan HBr and Guaifenesin',
    company: 'Preferred Pharmaceuticals, Inc',
    strength: 7,
    instructions: 'Release Celiac Artery, Open Approach',
    reason: 'Chronic follicular conjunctivitis, unspecified eye',
  },
  {
    name: 'conjugated estrogens',
    company: 'Physicians Total Care, Inc.',
    strength: 18,
    instructions: 'Resection of Bilateral Ovaries, Percutaneous Endoscopic Approach',
    reason: 'Change of job',
  },
  {
    name: 'Camphor',
    company: 'Rite Aid',
    strength: 3,
    instructions: 'Dilation of Esophagogastric Junction, Percutaneous Approach',
    reason: 'Unsp injury of intercostal blood vessels, unsp side, sequela',
  },
  {
    name: 'Oxygen',
    company: 'Frances Mahon Deaconess Hospital Home Oxygen',
    strength: 7,
    instructions:
      'Division of Right Lower Extremity Bursa and Ligament, Percutaneous Endoscopic Approach',
    reason: 'Poisoning by ganglionic blocking drugs, undetermined, init',
  },
  {
    name: 'tolterodine tartrate',
    company: 'Mylan Institutional Inc.',
    strength: 11,
    instructions: 'Plain Radiography of Left Vertebral Artery',
    reason: 'Corrosion of second degree of right forearm, subs encntr',
  },
  {
    name: 'hydrocortisone',
    company: 'L Perrigo Company',
    strength: 17,
    instructions: 'Resection of Right Large Intestine, Via Natural or Artificial Opening',
    reason: 'Poisoning by tetracyclines, intentional self-harm',
  },
  {
    name: 'IMIPRAMINE PAMOATE',
    company: 'STAT RX USA LLC',
    strength: 3,
    instructions: 'Reposition Left Metacarpal, External Approach',
    reason: 'Unsp fracture of fourth lumbar vertebra, init for opn fx',
  },
  {
    name: 'Dexamethasone',
    company: 'Roxane Laboratories, Inc',
    strength: 7,
    instructions:
      'Replacement of Right Greater Saphenous Vein with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Unsp mtrcy rider injured in collision w rail trn/veh nontraf',
  },
  {
    name: 'Triclosan',
    company: 'Delta Brands Inc',
    strength: 12,
    instructions:
      'Reposition Left Pelvic Bone with Internal Fixation Device, Percutaneous Endoscopic Approach',
    reason: 'Other fracture of shaft of right fibula',
  },
  {
    name: 'Lisinopril',
    company: 'Blu Pharmaceuticals, LLC',
    strength: 15,
    instructions: 'Removal of Intraluminal Device from Uterus and Cervix, External Approach',
    reason: 'Laceration w/o foreign body of unsp part of thorax, init',
  },
  {
    name: 'Polyethylene Glycol 3350',
    company: 'Cardinal Health',
    strength: 17,
    instructions: 'Fragmentation in Gallbladder, Via Natural or Artificial Opening Endoscopic',
    reason: 'Chronic instability of knee, left knee',
  },
  {
    name: 'Isosorbide Dinitrate',
    company: 'Cardinal Health',
    strength: 3,
    instructions:
      'Removal of Infusion Device from Cervicothoracic Vertebral Joint, Percutaneous Approach',
    reason: 'Displ simple suprcndl fx w/o intrcndl fx l humerus, init',
  },
  {
    name: 'beclomethasone dipropionate',
    company: 'Teva Respiratory, LLC',
    strength: 15,
    instructions: 'Excision of Lumbar Vertebra, Open Approach, Diagnostic',
    reason: 'Poisoning by anticoagulants, assault, initial encounter',
  },
  {
    name: 'Famotidine',
    company: 'Select Brand',
    strength: 18,
    instructions:
      'Fusion of Lumbosacral Joint with Autologous Tissue Substitute, Posterior Approach, Posterior Column, Percutaneous Approach',
    reason: 'Legal intervnt involving bayonet, bystander injured, init',
  },
  {
    name: 'Wintergreen Isopropyl Alcohol',
    company: 'Sunmark',
    strength: 12,
    instructions: 'Excision of Left External Jugular Vein, Open Approach',
    reason: 'Partial traumatic amputation at shoulder joint',
  },
  {
    name: 'Acyclovir',
    company: 'DAVA Pharmaceuticals, Inc.',
    strength: 17,
    instructions: 'Drainage of Upper Tooth, External Approach, All',
    reason: 'Abnormal radiolog finding on antenatal screening of mother',
  },
  {
    name: 'NAJA NAJA VENOM',
    company: 'RECEPTOPHARM INC',
    strength: 19,
    instructions:
      'Replacement of Anterior Neck Subcutaneous Tissue and Fascia with Synthetic Substitute, Percutaneous Approach',
    reason: 'Drug/chem diab with prolif diab rtnop w/o mclr edema, l eye',
  },
  {
    name:
      'Hydrastis Canadensis, Syzygium Jambolanum, Glandula Suprarenalis Suis, Pancreas Suis, Pituitary, Phaseolus',
    company: 'Energique, Inc.',
    strength: 20,
    instructions: 'Insertion of Internal Fixation Device into Left Femoral Shaft, Open Approach',
    reason: 'Strain of musc/fasc/tend at shoulder and upper arm level',
  },
  {
    name: 'Bur Oak',
    company: 'Antigen Laboratories, Inc.',
    strength: 12,
    instructions: 'Dilation of Left Main Bronchus, Via Natural or Artificial Opening',
    reason: 'Nondisp fx of coracoid process, unspecified shoulder',
  },
  {
    name: 'Benzocaine',
    company: 'Ultradent Products, Inc.',
    strength: 17,
    instructions:
      'Dilation of Left Popliteal Artery, Bifurcation, with Drug-eluting Intraluminal Device, Open Approach',
    reason: 'Unsp injury of musc/fasc/tend at forearm level, unsp arm',
  },
  {
    name: 'Standardized Sweet Vernal Grass Pollen',
    company: 'Nelco Laboratories, Inc.',
    strength: 3,
    instructions: 'Extirpation of Matter from Left Upper Leg Tendon, Open Approach',
    reason: 'Other in-line roller-skate accident, initial encounter',
  },
  {
    name: 'Eurotia lanata',
    company: 'Allermed Laboratories, Inc.',
    strength: 16,
    instructions: 'Fragmentation in Anus, Percutaneous Approach',
    reason: 'Other tetanus',
  },
  {
    name: 'zolpidem tartrate',
    company: 'Aphena Pharma Solutions - Tennessee, LLC',
    strength: 19,
    instructions: 'Excision of Scrotum, Percutaneous Endoscopic Approach',
    reason: 'Sprain of sternoclavicular (joint) (ligament), sequela',
  },
  {
    name: 'SULFACETAMIDE SODIUM, SULFUR',
    company: 'Mission Pharmacal Company',
    strength: 3,
    instructions:
      'Removal of Autologous Tissue Substitute from Left Thumb Phalanx, Percutaneous Endoscopic Approach',
    reason: 'Contusion of left front wall of thorax, initial encounter',
  },
  {
    name: 'Acetaminophen, Dextromethorphan HBr, Phenylephrine HCl',
    company: 'Meijer Distribution Inc',
    strength: 14,
    instructions:
      'Supplement Chest Wall with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Corrosion of second degree of trunk, unsp site, subs encntr',
  },
  {
    name: 'GLYCERIN',
    company: 'AMI Cosmetic Co.,Ltd.',
    strength: 3,
    instructions: 'Revision of Infusion Device in Left Carpal Joint, Percutaneous Approach',
    reason: 'Occupant of streetcar injured in unsp traf, sequela',
  },
  {
    name: 'METHYL SALICYLATE',
    company: 'AB7 Industries',
    strength: 11,
    instructions:
      'Removal of Nonautologous Tissue Substitute from Right Glenoid Cavity, Percutaneous Endoscopic Approach',
    reason: 'Nonrheumatic mitral (valve) prolapse',
  },
  {
    name: 'Lisinopril',
    company: 'REMEDYREPACK INC.',
    strength: 11,
    instructions: 'Hyperthermia of Soft Palate',
    reason: 'Poisoning by thrombolytic drug, undetermined, sequela',
  },
  {
    name: 'Cough Relief',
    company: 'Vitality Works, Inc',
    strength: 12,
    instructions: 'Repair Right Middle Lobe Bronchus, Percutaneous Approach',
    reason: 'Lymphoid leukemia, unspecified not having achieved remission',
  },
  {
    name: 'sulfacetamide sodium and prednisolone acetate',
    company: 'Physicians Total Care, Inc.',
    strength: 17,
    instructions:
      'Occlusion of Duodenum with Intraluminal Device, Via Natural or Artificial Opening Endoscopic',
    reason: 'Lacerat flexor musc/fasc/tend l thm at forarm lv, sequela',
  },
  {
    name: 'Dextrose',
    company: 'McKesson Packaging Services Business Unit of McKesson Corporation',
    strength: 2,
    instructions:
      'Removal of Synthetic Substitute from Right Metacarpophalangeal Joint, Percutaneous Endoscopic Approach',
    reason: 'Driver of 3-whl mv inj in clsn w 2/3-whl mv nontraf, sequela',
  },
  {
    name: 'SODIUM CHLORIDE',
    company: 'B. Braun Medical Inc.',
    strength: 17,
    instructions:
      'Drainage of Sacral Sympathetic Nerve with Drainage Device, Percutaneous Endoscopic Approach',
    reason: 'Nondisp bimalleol fx r low leg, subs for clos fx w malunion',
  },
  {
    name: 'ACETAMINOPHEN AND CODEINE PHOSPHATE',
    company: 'Apotheca, Inc.',
    strength: 10,
    instructions: 'Repair Right Rib, Percutaneous Approach',
    reason: 'Unsp fx upr end r tibia, 7thE',
  },
  {
    name:
      'Aconitum ferox, Adrenalinum, Aesculus hippocastanum, flos, Apis mellifica, Argentum nitricum, Avena sativa, Baptisia tinctoria, Mentha piperita, Myosotis arvensis, Phosphorus, Ranunculus bulbosus, Scleranthus annuus, flos, Scutellaria lateriflora, Sumbul, Thyroidinum, Verbena officinalis, flos, Viola odorata',
    company: 'King Bio Inc.',
    strength: 6,
    instructions: 'Destruction of Peritoneum, Open Approach',
    reason: 'Bitten by nonvenomous lizards, sequela',
  },
  {
    name: 'dextromethorphan hydrobromide and guaifenesin',
    company: 'Richmond Division of Wyeth',
    strength: 12,
    instructions: 'Removal of Internal Fixation Device from Right Ulna, Open Approach',
    reason: 'Poisoning by other narcotics, undetermined, sequela',
  },
  {
    name: 'Titanium dioxide',
    company: 'SHISEIDO AMERICAS CORPORATION',
    strength: 5,
    instructions: 'Revision of Infusion Device in Pancreas, External Approach',
    reason: 'Unspecified superficial injury of vagina and vulva, sequela',
  },
  {
    name: 'sumatriptan succinate',
    company: 'SUN PHARMACEUTICAL INDUSTRIES LIMITED',
    strength: 17,
    instructions: 'Revision of Neurostimulator Lead in Peripheral Nerve, Percutaneous Approach',
    reason: 'Sepsis of newborn due to Escherichia coli',
  },
  {
    name: 'verapamil hydrochloride',
    company: 'Lake Erie Medical DBA Quality Care Products LLC',
    strength: 1,
    instructions:
      'Introduction of Other Therapeutic Substance into Genitourinary Tract, Via Natural or Artificial Opening Endoscopic',
    reason: 'Nondisp fx of distal phalanx of right index finger, init',
  },
  {
    name: 'Zinc Oxide',
    company: 'Laboratorios Zepol S.A.',
    strength: 7,
    instructions: 'Removal of Intraluminal Device from Left Ear, Open Approach',
    reason: 'Underdosing of unspecified general anesthetics, init encntr',
  },
  {
    name: 'Lithium Carbonate',
    company: 'West-Ward Pharmaceutical Corp',
    strength: 3,
    instructions: 'Excision of Portal Vein, Percutaneous Approach, Diagnostic',
    reason: 'Toxic effect of venom of other venomous lizard',
  },
  {
    name: 'praziquantel',
    company: 'Bayer HealthCare Pharmaceuticals Inc.',
    strength: 4,
    instructions: 'Insertion of Ring External Fixation Device into Left Lower Femur, Open Approach',
    reason: 'Nondisp artic fx head of l femr, 7thE',
  },
  {
    name: 'TITANIUM DIOXIDE',
    company: 'CHANEL PARFUMS BEAUTE',
    strength: 11,
    instructions: 'Repair Cisterna Chyli, Open Approach',
    reason: 'Unspecified injury of popliteal vein, right leg, sequela',
  },
  {
    name: 'Triclosan',
    company: 'Kimberly-Clark Corporation',
    strength: 2,
    instructions:
      'Replacement of Right Internal Mammary Artery with Nonautologous Tissue Substitute, Open Approach',
    reason: 'Mech compl of unsp internal joint prosthesis, init encntr',
  },
  {
    name: 'Hydrogen Peroxide',
    company: 'Dyad Medical Sourcing, LLC',
    strength: 6,
    instructions: 'Bypass Right Atrium to Left Pulmonary Artery, Percutaneous Endoscopic Approach',
    reason: 'Person injured wh brd/alit from rail trn/veh, init',
  },
  {
    name: 'Carbon Dioxide Oxygen Mixture',
    company: 'Air Liquide America Specialty Gases LLC',
    strength: 19,
    instructions:
      'Restriction of Right Middle Lobe Bronchus, Via Natural or Artificial Opening Endoscopic',
    reason: 'Occ of anml-drn vehicle injured in oth and unsp trnsp acc',
  },
  {
    name: 'Simethicone',
    company: 'RUGBY LABORATORIES',
    strength: 14,
    instructions: 'Removal of Radioactive Element from Left Lower Extremity, Percutaneous Approach',
    reason: 'Toxic eff of halgn deriv of aliphatic hydrocrb, acc, init',
  },
  {
    name: 'Pulsatilla Tormentilla',
    company: 'Uriel Pharmacy Inc.',
    strength: 10,
    instructions: 'Removal of Infusion Device from Upper Intestinal Tract, External Approach',
    reason: 'Unsp physeal fracture of lower end of unspecified femur',
  },
  {
    name: 'Acetaminophen and Codeine Phosphate',
    company: 'Mylan Institutional Inc.',
    strength: 18,
    instructions:
      'Fusion of Thoracic Vertebral Joint with Autologous Tissue Substitute, Posterior Approach, Posterior Column, Percutaneous Approach',
    reason: 'Nondisp unsp fx left lesser toe(s), subs for fx w nonunion',
  },
  {
    name: 'Diphenhydramine Hydrochloride',
    company: 'Clinical Solutions Wholesale',
    strength: 9,
    instructions: 'Insertion of Infusion Device into Right External Carotid Artery, Open Approach',
    reason: 'Unsp soft tissue disorder related to use/pressure, r low leg',
  },
  {
    name: 'Lip Balm',
    company: 'Lornamead',
    strength: 11,
    instructions: 'Excision of Right Mastoid Sinus, Percutaneous Endoscopic Approach, Diagnostic',
    reason: 'Burn of 2nd deg mul sites of unsp ankle and foot, init',
  },
  {
    name: 'radish',
    company: 'Allergy Laboratories, Inc.',
    strength: 10,
    instructions:
      'Fusion of Left Finger Phalangeal Joint with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Inj intrinsic musc/fasc/tend finger at wrs/hnd lv, init',
  },
  {
    name: 'Amoxicillin and Clavulanate Potassium',
    company: 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC',
    strength: 9,
    instructions: 'Release Right Ventricle, Percutaneous Endoscopic Approach',
    reason: 'Sltr-haris Type III physl fx low end r femr, 7thD',
  },
  {
    name: 'Glycerin',
    company: 'AMI Cosmetic Co.,Ltd.',
    strength: 8,
    instructions:
      'Dilation of Left Renal Artery with Four or More Intraluminal Devices, Open Approach',
    reason: 'Ped w convey injured in collision w hv veh, unsp, subs',
  },
  {
    name: 'Ziprasidone HCl',
    company: 'Golden State Medical Supply, Inc.',
    strength: 16,
    instructions:
      'Dilation of Right Internal Mammary Artery with Two Drug-eluting Intraluminal Devices, Open Approach',
    reason: 'Superficial foreign body of left ring finger, init encntr',
  },
  {
    name: 'Dandelion',
    company: 'Nelco Laboratories, Inc.',
    strength: 9,
    instructions:
      'Supplement Left Metatarsal with Autologous Tissue Substitute, Percutaneous Approach',
    reason: 'Arthritis due to other bacteria, unspecified knee',
  },
  {
    name:
      'Aralia Quinquefolia, Hydrocotyle Asiatica, Polygonum Multiflorum, Hypothalamus, Pituitary, Germanium Sesquioxide',
    company: 'Synergy Formulas, Inc.',
    strength: 18,
    instructions:
      'Supplement Left Tunica Vaginalis with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Toxic effects of other corrosive organic compounds',
  },
  {
    name: 'Phenytoin Sodium',
    company: 'REMEDYREPACK INC.',
    strength: 1,
    instructions: 'Insertion of Infusion Device into Right Lung, Via Natural or Artificial Opening',
    reason: 'Other congenital malformations of digestive system',
  },
  {
    name: 'Salicylic Acid',
    company: 'H2O Plus',
    strength: 11,
    instructions: 'Drainage of Liver, Open Approach, Diagnostic',
    reason: 'Poisoning by chloramphenicol group, undetermined',
  },
  {
    name: 'fluticasone propionate and salmeterol',
    company: 'GlaxoSmithKline LLC',
    strength: 1,
    instructions:
      'Bypass Right Internal Iliac Artery to Bilateral External Iliac Arteries, Percutaneous Endoscopic Approach',
    reason: 'Burn 3rd deg mu sites of unsp lower limb, ex ank/ft, sqla',
  },
  {
    name: 'Pyrithione Zinc',
    company: 'The Kroger Co',
    strength: 1,
    instructions:
      'Transplantation of Cardiovascular System into Products of Conception, Via Natural or Artificial Opening',
    reason: 'Unspecified aircraft accident injuring occupant, subs encntr',
  },
  {
    name: 'Prednisone',
    company: 'Bryant Ranch Prepack',
    strength: 9,
    instructions: 'Hyperthermia, Single',
    reason: 'Unsp disp fx of second cervical vertebra, init for clos fx',
  },
  {
    name: 'acetaminophen, chlorpheniramine maleate, dextromethorphan HBr, phenylephrine HCl',
    company: 'Richmond Division of Wyeth',
    strength: 5,
    instructions: 'Supplement Left Cornea with Nonautologous Tissue Substitute, Open Approach',
    reason: 'Complete traum amp of unsp hip and thigh, level unsp, init',
  },
  {
    name: 'Nitrogen',
    company: 'Linde LLC',
    strength: 19,
    instructions:
      'Replacement of Right Thumb Phalanx with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Hit by falling object due to acc to inflatbl crft, sequela',
  },
  {
    name: 'Duloxetine',
    company: 'Zydus Pharmaceuticals (USA) Inc.',
    strength: 5,
    instructions:
      'Fusion of Lumbosacral Joint with Autologous Tissue Substitute, Posterior Approach, Posterior Column, Percutaneous Approach',
    reason: 'Nondisp longitud fx l patella, 7thJ',
  },
  {
    name: 'Doxycycline hyclate',
    company: 'Legacy Pharmaceutical Packaging',
    strength: 4,
    instructions: 'Drainage of Left Zygomatic Bone, Percutaneous Endoscopic Approach',
    reason: 'Pedl cyclst (driver) injured in unsp nontraf, subs',
  },
  {
    name: 'Fluticasone Propionate',
    company: 'Rebel Distributors Corp',
    strength: 11,
    instructions:
      'Fusion of Right Metatarsal-Tarsal Joint with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Underdosing of antiepileptic and sed-hypntc drugs, init',
  },
  {
    name: 'Simvastatin',
    company: 'NCS HealthCare of KY, Inc dba Vangard Labs',
    strength: 14,
    instructions: 'Removal of Other Device on Right Lower Arm',
    reason: 'Nondisp fx of l tibial tuberosity, 7thE',
  },
  {
    name: 'L Dopa',
    company: 'Energique, Inc.',
    strength: 20,
    instructions:
      'Insertion of Infusion Device into Left Ulnar Artery, Percutaneous Endoscopic Approach',
    reason: 'Injury of ulnar nerve at wrs/hnd lv of right arm, sequela',
  },
  {
    name: 'METHYL NICOTINATE, CAPSAICIN',
    company: 'Key 2 Health, Inc.',
    strength: 14,
    instructions:
      'Dilation of Tricuspid Valve with Drug-eluting Intraluminal Device, Open Approach',
    reason: 'Pasngr in hv veh injured in nonclsn trnsp accident in traf',
  },
  {
    name: 'Oxazepam',
    company: 'Bryant Ranch Prepack',
    strength: 6,
    instructions: 'Destruction of Left External Ear, Percutaneous Endoscopic Approach',
    reason: 'Oth physl fx lower end unsp femur, subs for fx w delay heal',
  },
  {
    name: 'Sotalol Hydrochloride',
    company: 'Upsher-Smith Laboratories, Inc.',
    strength: 8,
    instructions:
      'Computerized Tomography (CT Scan) of Bilateral Parotid Glands using Other Contrast, Unenhanced and Enhanced',
    reason: 'Disp fx of post wl of unsp acetab, subs for fx w delay heal',
  },
  {
    name: 'NAFCILLIN SODIUM',
    company: 'Teva Parenteral Medicines, Inc.',
    strength: 5,
    instructions: 'Removal of Monitoring Device from Lower Vein, Percutaneous Approach',
    reason: 'Nondisp transverse fracture of shaft of humerus, right arm',
  },
  {
    name: 'menthol',
    company: 'Premiere Enterprises',
    strength: 13,
    instructions:
      'Bypass Abdominal Aorta to Bilateral Femoral Arteries with Autologous Venous Tissue, Open Approach',
    reason: 'Corrosion of third degree of left scapular region, subs',
  },
  {
    name: 'NAJA NAJA VENOM',
    company: 'Receptopharm Inc.',
    strength: 12,
    instructions:
      'Bypass Duodenum to Ileum with Autologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Disorders of muscle in diseases classified elsewhere',
  },
  {
    name:
      'Agnus castus, Angelica sinensis, radix, Apis mellifica, Arnica montana, Cimicifuga racemosa, Estradiol, Estriol, Folliculinum,',
    company: 'ProBLEN',
    strength: 20,
    instructions: 'Excision of Left Trunk Tendon, Percutaneous Endoscopic Approach',
    reason: 'Disp fx of neck of unsp radius, subs for clos fx w nonunion',
  },
  {
    name: 'Acetaminophen and Codeine Phosphate',
    company: 'Hi-Tech Pharmacal Co., Inc.',
    strength: 11,
    instructions: 'Bypass Innominate Artery to Bilateral Upper Leg Artery, Open Approach',
    reason: 'Decreased fetal movements, second trimester, fetus 1',
  },
  {
    name: 'oxymorphone hydrochloride',
    company: 'Lake Erie Medical DBA Quality Care Products LLC',
    strength: 16,
    instructions: 'Repair Right Hand Artery, Open Approach',
    reason: 'Personal history of malignant neoplasm of larynx',
  },
  {
    name: 'METOPROLOL TARTRATE, ARGININE',
    company: 'Physician Therapeutics LLC',
    strength: 7,
    instructions:
      'Insertion of Monitoring Device into Esophagus, Via Natural or Artificial Opening Endoscopic',
    reason: 'Massive umbilical hemorrhage of newborn',
  },
  {
    name: 'Menthol',
    company: 'Unifirst First Aid Corporation',
    strength: 8,
    instructions:
      'Revision of Intraluminal Device in Urethra, Via Natural or Artificial Opening Endoscopic',
    reason: 'Laceration of intercostal blood vessels, unsp side, init',
  },
  {
    name: 'eszopiclone',
    company: 'Roxane Laboratories, Inc.',
    strength: 20,
    instructions: 'Occlusion of Right Vas Deferens with Extraluminal Device, Percutaneous Approach',
    reason: 'Disp fx of nk of 1st MC bone, l hand, subs for fx w nonunion',
  },
  {
    name: 'Argentum 6',
    company: 'Uriel Pharmacy Inc.',
    strength: 1,
    instructions: 'Removal of Monitoring Device from Kidney, Via Natural or Artificial Opening',
    reason: 'Poisoning by unspecified topical agent, assault',
  },
  {
    name: 'VENLAFAXINE HYDROCHLORIDE',
    company: 'Major Pharmaceuticals',
    strength: 3,
    instructions: 'Reposition Gastric Vein, Percutaneous Approach',
    reason: 'Focal chorioretin inflam, macular or paramacular, unsp eye',
  },
  {
    name: 'DOXYCYCLINE',
    company: 'Lupin Pharmaceuticals, Inc.',
    strength: 13,
    instructions:
      'Supplement Right Tympanic Membrane with Nonautologous Tissue Substitute, Open Approach',
    reason: 'Lacerat unsp blood vessel at lower leg level, left leg, init',
  },
  {
    name: 'RHODIUM',
    company: 'Natural Health Supply',
    strength: 6,
    instructions: 'Release Left Foot Bursa and Ligament, Percutaneous Approach',
    reason: 'Aggressive periodontitis, generalized, unspecified severity',
  },
  {
    name: 'Metoclopramide Hydrochloride',
    company: 'Watson Laboratories, Inc.',
    strength: 16,
    instructions: 'Excision of Left Femoral Shaft, Percutaneous Approach',
    reason: 'Other articular cartilage disorders, unspecified hip',
  },
  {
    name: 'OCTINOXATE, TITANIUM DIOXIDE',
    company: 'Napoleon Perdis Cosmetics, Inc',
    strength: 2,
    instructions:
      'Removal of Nonautologous Tissue Substitute from Right Finger Phalanx, Open Approach',
    reason: 'Inj unsp musc/fasc/tend at thigh level, right thigh, sequela',
  },
  {
    name: 'COTTON FIBER',
    company: 'Chrio Korea Co., Ltd',
    strength: 15,
    instructions: 'Drainage of Right Carpal, Percutaneous Endoscopic Approach, Diagnostic',
    reason: 'Assault by paintball gun discharge',
  },
  {
    name: 'Ibuprofen',
    company: "Dr. Reddy's Laboratories Limited",
    strength: 2,
    instructions: 'Beam Radiation of Other Bone using Electrons, Intraoperative',
    reason: 'Abdominal migraine, intractable',
  },
  {
    name: 'diphenhydramine hydrochloride and zinc acetate',
    company: 'Meijer Distribution Inc',
    strength: 14,
    instructions: 'Removal of Nonautologous Tissue Substitute from Lumbosacral Disc, Open Approach',
    reason: 'Displ intertroch fx r femur, subs for clos fx w delay heal',
  },
  {
    name: 'Diltiazem Hydrochloride',
    company: 'Valeant Pharmaceuticals North America LLC',
    strength: 12,
    instructions: 'Male Reproductive System, Change',
    reason: 'Maternal care for viable fetus in abd preg, unsp tri, oth',
  },
  {
    name: 'Bahia Grass',
    company: 'Nelco Laboratories, Inc.',
    strength: 19,
    instructions: 'Repair Supernumerary Breast, External Approach',
    reason: 'Car driver injured in clsn w pick-up truck nontraf, sequela',
  },
  {
    name: 'Fluvoxamine Maleate',
    company: 'Par Pharmaceutical, Inc.',
    strength: 7,
    instructions: 'Release Right Internal Iliac Artery, Open Approach',
    reason: 'Inj oth blood vessels at hip and thigh level, unsp leg, init',
  },
  {
    name: 'URSODIOL',
    company: 'Global Pharmaceuticals, Division of Impax Laboratories, Inc.',
    strength: 18,
    instructions:
      'Bypass Portal Vein to Lower Vein with Autologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Oth fx right patella, subs for opn fx type 3A/B/C w nonunion',
  },
  {
    name: 'Acetaminophen',
    company: 'Kroger Company',
    strength: 15,
    instructions: 'Excision of Left Abdomen Tendon, Open Approach',
    reason: 'Enophthalmos due to trauma or surgery, left eye',
  },
  {
    name: 'Pyrithione zinc',
    company: 'Family Dollar Services, Inc.',
    strength: 13,
    instructions:
      'Bypass Middle Esophagus to Duodenum with Nonautologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic',
    reason: 'Legal intervnt involving oth means, suspect injured, subs',
  },
  {
    name: 'MAGNESIUM HYDROXIDE',
    company: 'Select Brand',
    strength: 13,
    instructions: 'Insertion of Internal Fixation Device into Right Lacrimal Bone, Open Approach',
    reason: 'Toxic effect of venom of ants, assault, sequela',
  },
  {
    name: 'HUMAN RABIES VIRUS IMMUNE GLOBULIN',
    company: 'Sanofi Pasteur Inc.',
    strength: 18,
    instructions: 'Release Aortic Body, Open Approach',
    reason: 'Other specified peripheral vascular diseases',
  },
  {
    name: 'enoxaparin sodium',
    company: 'sanofi-aventis U.S. LLC',
    strength: 10,
    instructions: 'Monitoring of Arterial Sound, Peripheral, Percutaneous Approach',
    reason: 'Corros second degree of unsp mult fngr (nail), not inc thumb',
  },
  {
    name: 'TITANIUM DIOXIDE',
    company: 'CLINIQUE LABORATORIES INC',
    strength: 14,
    instructions: 'Dilation of Urethra, Via Natural or Artificial Opening',
    reason: 'Oligohydramnios, first trimester, not applicable or unsp',
  },
  {
    name: 'OCTINOXATE and TITANIUM DIOXIDE',
    company: 'SHISEIDO AMERICA INC.',
    strength: 4,
    instructions:
      'Supplement Left Trunk Muscle with Autologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Displacement of oth bone devices, implants and grafts, init',
  },
  {
    name: 'Alcohol',
    company: 'Bath & Body Works, Inc.',
    strength: 10,
    instructions:
      'Insertion of Radioactive Element into Prostate, Via Natural or Artificial Opening',
    reason: 'Oth superfic bite of right eyelid and periocular area, subs',
  },
  {
    name: 'Hackberry',
    company: 'Antigen Laboratories, Inc.',
    strength: 2,
    instructions:
      'Insertion of Hybrid External Fixation Device into Left Humeral Head, Percutaneous Approach',
    reason: 'Posterior dislocation of left humerus, initial encounter',
  },
  {
    name: 'Acyclovir',
    company: 'REMEDYREPACK INC.',
    strength: 15,
    instructions:
      'Occlusion of Left Brachial Vein with Intraluminal Device, Percutaneous Endoscopic Approach',
    reason: 'Disp fx of medial phalanx of left ring finger, sequela',
  },
  {
    name: 'Metformin Hydrochloride',
    company: 'PD-Rx Pharmaceuticals, Inc.',
    strength: 7,
    instructions: 'Reposition Right Thorax Muscle, Percutaneous Endoscopic Approach',
    reason: 'Sltr-haris Type I physeal fracture of right metatarsal, 7thP',
  },
  {
    name: 'Pyrithione Zinc',
    company: 'Conopco Inc. d/b/a Unilever',
    strength: 20,
    instructions: 'Restriction of Bladder with Extraluminal Device, Open Approach',
    reason: 'Postproc hematoma of right eye and adnexa fol other proc',
  },
  {
    name: 'OFLOXACIN',
    company: 'Cadila Pharmaceuticals Limited',
    strength: 5,
    instructions: 'Excision of Left Cephalic Vein, Open Approach',
    reason: 'Blister (nonthermal), unspecified hip, sequela',
  },
  {
    name: 'Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl',
    company: 'Supervalu Inc',
    strength: 8,
    instructions:
      'Occlusion of Right Fallopian Tube with Extraluminal Device, Percutaneous Endoscopic Approach',
    reason: 'Laceration of tail of pancreas, unsp degree, subs encntr',
  },
  {
    name: 'Fluticasone Propionate',
    company: 'Proficient Rx LP',
    strength: 9,
    instructions: 'Removal of Drainage Device from Abdominal Wall, Open Approach',
    reason: 'Courtyard of prison as place',
  },
  {
    name: 'Indapamide',
    company: 'Actavis Elizabeth LLC',
    strength: 4,
    instructions:
      'Nonimaging Nuclear Medicine Assay of Kidneys, Ureters and Bladder using Iodine 123 (I-123)',
    reason: 'Separation of retinal layers',
  },
  {
    name: 'penicillin G potassium',
    company: 'Roerig',
    strength: 5,
    instructions: 'Excision of Mesentery, Percutaneous Approach',
    reason: 'Traum hemor left cerebrum w LOC of 31-59 min, subs',
  },
  {
    name: 'furosemide',
    company: 'Bryant Ranch Prepack',
    strength: 13,
    instructions:
      'Fragmentation in Left Kidney Pelvis, Via Natural or Artificial Opening Endoscopic',
    reason: 'Synovial hypertrophy, not elsewhere classified, thigh',
  },
  {
    name: 'Buspirone hydrochloride',
    company: 'Zydus Pharmaceuticals (USA) Inc.',
    strength: 5,
    instructions: 'Supplement Right Atrium with Zooplastic Tissue, Percutaneous Approach',
    reason: 'Other spondylosis, cervical region',
  },
  {
    name: 'Aspirin',
    company: 'Unifirst First Aid Corporation',
    strength: 1,
    instructions: 'Supplement Lower Jaw with Synthetic Substitute, Open Approach',
    reason: 'Contact with nail gun',
  },
  {
    name: 'Acetaminophen',
    company: 'Cardinal Health',
    strength: 13,
    instructions:
      'Insertion of Ring External Fixation Device into Right Lower Femur, Percutaneous Endoscopic Approach',
    reason: 'Oth foreign object in oth prt resp tract causing asphyx',
  },
  {
    name:
      'Aconitum Napellus, Antimonium Tartaricum, Belladonna, Bryonia, Hyoscyamus Niger, Ipecacuanha, Lobelia Inflata',
    company: 'Deseret Biologicals, Inc',
    strength: 10,
    instructions: 'Destruction of Left Upper Extremity Bursa and Ligament, Percutaneous Approach',
    reason: 'Oth fx upr & low end r fibula, 7thM',
  },
  {
    name:
      'LEUCINE, LYSINE, ISOLEUCINE, VALINE, HISTIDINE, PHENYLALANINE, THREONINE, METHIONINE, TRYPTOPHAN, TYROSINE, N-ACETYL-TYROSINE, ARGININE, PROLINE, ALANINE, GLUTAMIC ACIDE, SERINE, GLYCINE, ASPARTIC ACID, TAURINE, CYSTEINE HYDROCHLORIDE',
    company: 'Baxter Healthcare Corporation',
    strength: 15,
    instructions: 'Division of Right Trunk Bursa and Ligament, Percutaneous Approach',
    reason: 'Disorders of optic chiasm',
  },
  {
    name: 'Bacitracin Zinc',
    company: 'The Great Atlantic & Pacific Tea Company',
    strength: 18,
    instructions: 'Revision of Internal Fixation Device in Left Carpal, Open Approach',
    reason: 'Encounter for surveillance of injectable contraceptive',
  },
  {
    name: 'TOXICODENDRON RADICANS LEAF, CROTON TIGLIUM SEED, and XEROPHYLLUM ASPHODELOIDES',
    company: "Hyland's",
    strength: 16,
    instructions: 'Occlusion of Pulmonary Valve, Open Approach',
    reason: 'Calcific tendinitis, right forearm',
  },
  {
    name: 'Sodium Fluoride',
    company: 'Crosstex International Inc.',
    strength: 9,
    instructions: 'Osteopathic Treatment of Abdomen using General Mobilization',
    reason: 'Burn of third degree of left foot, subsequent encounter',
  },
  {
    name: 'Disulfiram',
    company: 'Rising Pharmaceuticals, Inc.',
    strength: 7,
    instructions:
      'Occlusion of Left Upper Extremity Lymphatic with Intraluminal Device, Percutaneous Endoscopic Approach',
    reason: 'Unsp athscl nonaut bio bypass of the extrm, unsp extremity',
  },
  {
    name:
      'Acetaminophen, Dextromethorphan Hydrobromide, Diphenhydramine Hydrochloride, Guaifenesin, and Phenylephrine Hydrochloride',
    company: 'Reckitt Benckiser LLC',
    strength: 12,
    instructions: 'Removal of Spacer from Lumbosacral Joint, Open Approach',
    reason: 'Adverse effect of smallpox vaccines',
  },
  {
    name: 'Isopropyl Alcohol',
    company: 'Good Neighbor Pharmacy',
    strength: 7,
    instructions: 'Extirpation of Matter from Left Lacrimal Gland, External Approach',
    reason: 'Monocular esotropia with A pattern',
  },
  {
    name: 'Sulfamethoxazole and Trimethoprim',
    company: 'Glenmark Generics Inc. USA',
    strength: 10,
    instructions:
      'Motor Function Treatment of Integumentary System - Whole Body using Assistive, Adaptive, Supportive or Protective Equipment',
    reason: 'Post disp fx of sternal end unsp clavicle, 7thK',
  },
  {
    name: 'Benzocaine',
    company: 'Coty US LLC',
    strength: 16,
    instructions: 'Extraction of Femoral Nerve, Percutaneous Endoscopic Approach',
    reason: 'Nondisp fx of greater tuberosity of l humer, 7thP',
  },
  {
    name: 'Tramadol Hydrochloride Extended-Release Tablets',
    company: 'Par Pharmaceutical, Inc.',
    strength: 9,
    instructions:
      'Supplement Lumbosacral Disc with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Lacerat msl/fasc/tnd post grp at thi lev, right thigh, subs',
  },
  {
    name: 'pilocarpine hydrochloride',
    company: 'Alcon Laboratories, Inc.',
    strength: 14,
    instructions: 'Release Nose, External Approach',
    reason: 'Prsn outsd pk-up/van inj in clsn w 2/3-whl mv nontraf, subs',
  },
  {
    name: 'IRIS VERSICOLOR ROOT',
    company: 'Natural Health Supply',
    strength: 4,
    instructions:
      'Computerized Tomography (CT Scan) of Right and Left Heart using Low Osmolar Contrast',
    reason: 'Monoplg upr lmb following unsp cerebrovascular disease',
  },
  {
    name: 'Tetracycline Hydrochloride',
    company: 'Physicians Total Care, Inc.',
    strength: 18,
    instructions: 'Revision of Autologous Tissue Substitute in Male Perineum, Open Approach',
    reason: 'Displ transverse fx shaft of unsp femr, 7thM',
  },
  {
    name: 'pioglitazone hydrochloride',
    company: 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC',
    strength: 5,
    instructions: 'Drainage of Vagus Nerve with Drainage Device, Open Approach',
    reason: 'Unsp pedl cyclst injured in clsn w ped/anml in traf, subs',
  },
  {
    name: 'BACLOFEN',
    company: 'STAT RX USA LLC',
    strength: 14,
    instructions:
      'Fusion of Cervicothoracic Vertebral Joint with Autologous Tissue Substitute, Anterior Approach, Anterior Column, Open Approach',
    reason: 'Explosion and rupture of boiler, initial encounter',
  },
  {
    name: 'Gabapentin',
    company: 'TYA Pharmaceuticals',
    strength: 6,
    instructions:
      'Supplement Abducens Nerve with Autologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Corrosion of unsp degree of back of right hand, init encntr',
  },
  {
    name: 'benzalkonium chloride',
    company: 'BIC Graphic USA Manufacturing Co, Inc.',
    strength: 19,
    instructions:
      'Removal of Autologous Tissue Substitute from Right Sacroiliac Joint, Percutaneous Endoscopic Approach',
    reason: 'Other injury of uterus, subsequent encounter',
  },
  {
    name:
      'Arsenicum album, Coffea cruda, Kali carbonicum, Magnesia carbonica, Nux vomica, Passiflora incarnata, Sepia, Valeriana officinalis,',
    company: 'Apotheca Company',
    strength: 7,
    instructions: 'Removal of Nonautologous Tissue Substitute from Right Eye, External Approach',
    reason: 'Carcinoma in situ of digestive organ, unspecified',
  },
  {
    name: 'Topical Skin Relief',
    company: 'Vitality Works, Inc',
    strength: 9,
    instructions:
      'Replacement of Aortic Valve with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    reason: 'Postthrombotic syndrome w/o complications of unsp extremity',
  },
  {
    name: 'Epinephrine',
    company: 'Dispensing Solutions, Inc.',
    strength: 19,
    instructions: 'Repair Aortic Valve, Open Approach',
    reason: 'Unsp fx navicular bone of right wrist, init for opn fx',
  },
  {
    name: 'Oxymorphone Hydrochloride',
    company: 'KVK-Tech, Inc.',
    strength: 19,
    instructions:
      'Insertion of Monitoring Device into Left Pulmonary Artery, Percutaneous Endoscopic Approach',
    reason: 'Nondisp fx of base of second metacarpal bone, right hand',
  },
  {
    name: 'SALICYLIC ACID',
    company: 'Halogent, LLC (DBA Exposed Skin Care)',
    strength: 19,
    instructions: 'Drainage of Right Foot Muscle, Percutaneous Endoscopic Approach',
    reason: 'Person outside pk-up/van inj in clsn w hv veh in traf, init',
  },
  {
    name: 'TITANIUM DIOXIDE',
    company: 'CLINIQUE LABORATORIES INC.',
    strength: 17,
    instructions: 'Beam Radiation of Adrenal Glands using Neutrons',
    reason: 'Superficial frostbite of left hand, initial encounter',
  },
  {
    name: 'Mefloquine Hydrochloride',
    company: 'Sandoz Inc',
    strength: 18,
    instructions: 'Transfer Facial Nerve to Trochlear Nerve, Open Approach',
    reason: 'Displaced transcondylar fracture of unsp humerus, init',
  },
  {
    name: 'Hydrocodone Bitartrate and Acetaminophen',
    company: 'Libertas Pharma, Inc.',
    strength: 17,
    instructions: 'Division of Right Abdomen Tendon, Percutaneous Endoscopic Approach',
    reason: 'Spontaneous rupture of extensor tendons, forearm',
  },
  {
    name: 'benzocaine and menthol',
    company: 'Combe Incorporated',
    strength: 11,
    instructions: 'Excision of Right Knee Tendon, Percutaneous Endoscopic Approach, Diagnostic',
    reason: 'Ankylosis, left hand',
  },
  {
    name: 'PULSATILLA VULGARIS and SULFUR and CORTISONE ACETATE',
    company: 'Heel Inc',
    strength: 18,
    instructions:
      'Bypass Right Kidney Pelvis to Left Kidney Pelvis with Synthetic Substitute, Percutaneous Endoscopic Approach',
    reason: 'Maternal care for anti-D antibodies, unsp trimester, oth',
  },
  {
    name: 'spironolactone',
    company: 'Unit Dose Services',
    strength: 16,
    instructions: 'Removal of Synthetic Substitute from Right Scapula, Percutaneous Approach',
    reason: 'Osteophyte, right hip',
  },
  {
    name: 'Diphenhydramine HCl',
    company: 'SMART SENSE (Kmart)',
    strength: 11,
    instructions:
      'Dilation of Left Renal Artery with Intraluminal Device, Percutaneous Endoscopic Approach',
    reason: 'Injury of other blood vessels at forearm level',
  },
  {
    name: 'estradiol',
    company: 'Warner Chilcott (US), LLC',
    strength: 7,
    instructions:
      'Occlusion of Left Lower Lobe Bronchus with Intraluminal Device, Via Natural or Artificial Opening Endoscopic',
    reason: 'Crushing injury of unspecified foot, subsequent encounter',
  },
  {
    name: 'Pistachio',
    company: 'Nelco Laboratories, Inc.',
    strength: 12,
    instructions: 'Reposition Left Wrist Joint, Percutaneous Endoscopic Approach',
    reason: 'Other mature T/NK-cell lymphomas, intrapelvic lymph nodes',
  },
  {
    name: 'Acetaminophen',
    company: 'Unifirst First Aid Corporation',
    strength: 20,
    instructions: 'Supplement Left Common Iliac Artery with Synthetic Substitute, Open Approach',
    reason: 'Toxic effect of venom of gila monster, self-harm, init',
  },
  {
    name: 'piroxicam',
    company: 'Greenstone LLC',
    strength: 18,
    instructions:
      'Muscle Performance Treatment of Integumentary System - Lower Back / Lower Extremity using Orthosis',
    reason: 'Unsp traum displ spondylolysis of fifth cervcal vert, init',
  },
];
